[deploy]
bucket = 'cfn-artifacts-tim'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
NetworkingStack = 'CrdNet'
ClusterStack = 'CrdCluster'
TaskDefinitionStack = 'CrdSrvTaskDef'
