AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Task Definition File
  Fargate Service
  Execution Role
  Task Role

Parameters:
  NetworkingStack:
    Type: String
    Description: This is our base layer of networking components eg. VPC
    Default: CrdNet
  ClusterStack:
    Type: String
    Description: This is our cluster layer eg. ECS Cluster, ALB
    Default: CrdCluster
  TaskDefinitionStack:
    Type: String
    Description: This is our task definition stack for backend service
    Default: CrdSrvTaskDef
  ContainerPort:
    Type: Number
    Default: 4567
  ServiceName:
    Type: String
    Default: backend-flask

Resources:
  FargateService:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub "${ClusterStack}ClusterName"
      DeploymentController: 
        Type: ECS
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 0
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn: 
            Fn::ImportValue:
              !Sub "${ClusterStack}BackendTGArn"
          ContainerName: 'backend-flask'
          ContainerPort: !Ref ContainerPort
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: 
                !Sub "${ClusterStack}ServiceSecurityGroupId"
          Subnets:
            Fn::Split:
              - ","
              - Fn::ImportValue: 
                  !Sub "${NetworkingStack}PublicSubnetIds"
      PlatformVersion: LATEST
      PropagateTags: SERVICE
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: cruddur-2
        # TODO - If you want to log
        # LogConfiguration
        Services:
          - DiscoveryName: backend-flask
            PortName: backend-flask
            ClientAliases:
              - Port: !Ref ContainerPort
      # ServiceRegistries:
      #   - RegistryArn: !Sub "arn::aws::servicediscovery:${AWS::Region}:${AWS::AccountId}:service/srv-cruddur-backend-flask"
      #     Port: !Ref ContainerPort
      #     ContainerName: !Ref ContainerName
      #     ContainerPort: !Ref ContainerPort
      ServiceName: !Ref ServiceName
      TaskDefinition: 
       Fn::ImportValue:
        !Sub "${TaskDefinitionStack}TaskDefinition"

Outputs:
  ServiceName:
   Value: !GetAtt FargateService.Name
   Export:
    Name: !Sub "${AWS::StackName}ServiceName"