[deploy]
bucket = 'cfn-artifacts-tim'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GithubBranch = 'prod'
GithubRepo = 'timmy-cde/aws-bootcamp-cruddur-2023'
ArtifactBucketName = 'cfn-codepipeline-cruddur-artifacts-tim'