name: "Sync Static Website (Frontend)"
run-name: "Deploy Site Run: ${{ github.run_id }}"

on:
  push:
    branches: 
    - prod

jobs:
  build-and-sync-frontend:
   runs-on: "ubuntu-latest"
   steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name:  Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Build Frontend
      env:
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
        REACT_APP_FRONTEND_URL: ${{ secrets.REACT_APP_FRONTEND_URL }}
        REACT_APP_AWS_PROJECT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        REACT_APP_AWS_COGNITO_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        REACT_APP_AWS_USER_POOLS_ID: ${{ secrets.REACT_APP_AWS_USER_POOLS_ID }}
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID}} 
        REACT_APP_API_GATEWAY_ENDPOINT: ${{ secrets.REACT_APP_API_GATEWAY_ENDPOINT }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        CI: false
      run: |
        cd frontend-react-js
        npm ci
        npm run build
    
    - name: Setup Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "3.1"
    
    - name: Sync static site
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        GITHUB_ACTIONS_WORKFLOW: true
      run: |
        echo "===========Installing gems==========="
        bundle install
        bundle update --bundler
        echo "=====Generating frontedn env vars===="
        bin/frontend/generate-env
        echo "==============Syncing================"
        bin/frontend/sync
